# ==========================================
# REGLAS DE ACCESO (ACL) - EQUIPO HECTOR
# ==========================================

# ------------------------------------------
# 1. CLIENTE: MKR1000
# ------------------------------------------
user mkr1000
# Permisos de escritura (W) - Envío de datos de sensores
topic write smarthome/equipoHector/temperatura
topic write smarthome/equipoHector/humedad
topic write smarthome/equipoHector/gas/mq6
topic write smarthome/equipoHector/gas/mq7
topic write smarthome/equipoHector/sonido/microfono
# Permisos de lectura (R) - Control de actuadores
topic read smarthome/equipoHector/control/led

# ------------------------------------------
# 2. CLIENTE: ESP32 CAM
# ------------------------------------------
user esp32cam
# Permisos de escritura (W) - Envío de eventos de imagen/persona
topic write smarthome/equipoHector/camara/evento
topic write smarthome/equipoHector/prediccion/temperatura

# ------------------------------------------
# 3. CLIENTE: NODE-RED
# ------------------------------------------
user nodered
# Permisos de lectura (R) - Recepción de todos los sensores y cámara
topic read smarthome/equipoHector/temperatura
topic read smarthome/equipoHector/humedad
topic read smarthome/equipoHector/gas/mq6
topic read smarthome/equipoHector/gas/mq7
topic read smarthome/equipoHector/sonido/microfono
topic read smarthome/equipoHector/camara/evento
topic read smarthome/equipoHector/prediccion/temperatura

# Permisos de escritura (W) - Envío de comandos físicos
topic write smarthome/equipoHector/control/led
topic write smarthome/equipoHector/alerta

# Permisos de escritura (W) - Tópicos obligatorios del LLM
topic write smarthome/equipoHector/llm/decision
topic write smarthome/equipoHector/llm/respuesta

# Permiso COAP
topic readwrite smarthome/equipoHector/coap/temperatura

# ------------------------------------------
# 4. CLIENTE: ADMINISTRADOR / DEPURACIÓN
# ------------------------------------------
user mi_usuario
topic readwrite #