# --- Listener estándar (sin cifrar) ---
listener 1883
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl.conf

# --- Listener seguro (TLS) ---
listener 8883
allow_anonymous false
password_file /mosquitto/config/passwd
certfile /mosquitto/config/certs/server.crt
keyfile /mosquitto/config/certs/server.key
acl_file /mosquitto/config/acl.conf

#tls_version tlsv1.2